# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
  end
  config.vbguest.auto_update = false

  config.vm.provision "shell", path: 'dependencies.sh'
end
