# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "server_box"
  config.vm.network "public_network", bridge: "wlp5s0", ip: ENV['IP']
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
  end
  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant", :disabled => true
  config.vm.provision "shell", path: '../initServer.sh', args: "#{ENV['PATH_BACKUP']} #{ENV['IP_BACKUP']} #{ENV['ROUTE_MIDDLE']}"   
end
